  - name: Add Docker GPG key
    apt_key: 'url={{ubuntu_docker_gpg_key}}'

  - name: Add Docker APT repository
    apt_repository:
      repo: 'deb [arch=amd64] {{ubuntu_docker_repo}} {{ansible_distribution_release}} stable'

  - name: Install list of packages
    apt:
      name: '{{ubuntu_docker_packages}}'
      state: present
      update_cache: yes     

